# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    ports:
      - 5058:5058

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: db
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./db-data:/var/lib/mysql:z
    # https://github.com/docker/compose/issues/9367
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 30s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
